return {
	"stevearc/overseer.nvim",
	cmd = {
		"OverseerOpen",
		"OverseerClose",
		"OverseerToggle",
		"OverseerSaveBundle",
		"OverseerLoadBundle",
		"OverseerDeleteBundle",
		"OverseerRunCmd",
		"OverseerRun",
		"OverseerInfo",
		"OverseerBuild",
		"OverseerQuickAction",
		"OverseerTaskAction",
		"OverseerClearCache",
	},
	opts = {
		dap = false,
		templates = { "builtin", "user.xmake" },
		default_template_prompt = "always",
		form = { border = "single" },
		confirm = { border = "single" },
		task_win = { border = "single" },
		help_win = { border = "single" },
	},
	keys = {
		{ "<leader>oa", "<cmd>OverseerTaskAction<cr>", desc = "Task action" },
		{ "<leader>ob", "<cmd>OverseerBuild<cr>", desc = "Task builder" },
		{ "<leader>oc", "<cmd>OverseerClearCache<cr>", desc = "Clear cache" },
		{ "<leader>ol", "<cmd>OverseerToggle<cr>", desc = "Task list" },
		{ "<leader>or", "<cmd>OverseerRun<cr>", desc = "Run task" },
	},
}
