return {
	"nvim-treesitter/nvim-treesitter",
	opts = {
		ensure_installed = {
			"arduino",
			"bash",
			"c",
			"cmake",
			"comment",
			"cpp",
			"css",
			"glsl",
			"html",
			"javascript",
			"json",
			"json5",
			"jsonc",
			"lua",
			"luadoc",
			"luap",
			"make",
			"markdown",
			"markdown_inline",
			"python",
			"query",
			"regex",
			"tsx",
			"typescript",
			"vim",
			"vimdoc",
			"yaml",
		},
		highlight = { enable = true },
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<bs>",
			},
		},
	},
	config = function(_, opts)
		require("nvim-treesitter.configs").setup(opts)
	end,
}
